### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by Gotr-byte** [Gotr-byte/Transcendence#3]
Am trying to fetch by frontend, am not able possiby due to CORS.

**Comment by Gotr-byte** [comment]
CORS (Cross-Origin Resource Sharing) Issue: If your React app is running on a different origin (like localhost:3000) and the server on another (like localhost:4000), then you might run into CORS issues. The server should be set up to send appropriate CORS headers to allow requests from your React app's origin. If you have control over the server, you can use middleware/packages like cors for Express to handle this.

**Comment by dfm39** [comment]
Problem is resolved, setup cors now. when implementing fetch requests, make sure to include the credentials like this:
```
fetch("http://localhost:4000/users/all", {
      credentials: "include",
    }) 
```
changes are on branch fetchingFix

**Comment by dfm39** [comment]
Problem is resolved, setup cors now. when implementing fetch requests, make sure to include the credentials like this:
```
fetch("http://localhost:4000/users/all", {
      credentials: "include",
    }) 
```
changes are on branch fetchingFix

**Comment by dfm39** [comment]
Problem is resolved, setup cors now. when implementing fetch requests, make sure to include credentials like this:
```
fetch("http://localhost:4000/users/all", {
      credentials: "include",
    }) 
```
changes are on branch fetchingFix
