### ISSUE TITLE
Fetching Fix issue

### ISSUE THREAD

**Issue by Gotr-byte** [Gotr-byte/Transcendence#5]
I ran docker-compose in the fetchingFix, when running: docker-compose up I encountered the the following error message:

~/transcendence$ docker-compose up
WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BUILD_TARGET" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BACKEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BACKEND_PORT" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'Ports': No port specified: :

**Comment by dfm39** [comment]
Oh yeah, make sure to use the new .env file :)

**Comment by Gotr-byte** [comment]
Gotcha!
