### ISSUE TITLE
issue seen on Brave browser during login, some library is depreceted

### ISSUE THREAD

**Issue by Gotr-byte** [Gotr-byte/Transcendence#76]
![image](https://github.com/Gotr-byte/Transcendence/assets/82155525/1ebeea6e-5802-4f75-a7f5-1d102a010d94)

**Comment by dfm39** [comment]
maybe npm update in the frontend folder fixes it

**Comment by Gotr-byte** [comment]
hmm it maybe my browser

**Comment by Gotr-byte** [comment]
issue occurs on other sites in Brave, must have been my browser issue

**Comment by Gotr-byte** [comment]
Checked with chrome, no warning on chrome
